### ISSUE TITLE
Feedback (for React questions)

### ISSUE THREAD

**Issue by yeskunall** [FAQGURU/FAQGURU#2]
Hey 👋🏽

This looks like a good resource for interview questions—I haven’t had a chance to go through all of them.

I’m primarily a front-end developer, so I jumped straight to the React interview questions, and was quite surprised to see that most of the questions seem to be wrongly mislabelled. For example, [this](https://github.com/FAQGURU/FAQGURU/blob/master/topics/en/react.md#whats-an-alternative-way-to-avoid-having-to-bind-to-this-in-event-callback-methods-senior) question:

> What's an alternative way to avoid having to bind to this in event callback methods? (Senior)

... is definitely not a senior React-developer question. I’ve been asked this question several times before (for intern positions), and I’m no senior developer 😆

Same goes for [this](https://github.com/FAQGURU/FAQGURU/blob/master/topics/en/react.md#what-is-the-point-of-using-keys-in-react-senior), [this](https://github.com/FAQGURU/FAQGURU/blob/master/topics/en/react.md#name-the-different-lifecycle-methods-senior), [this](https://github.com/FAQGURU/FAQGURU/blob/master/topics/en/react.md#name-the-different-lifecycle-methods-senior) question—there’s actually quite a few, the more I look into it.

Another thing: for [this](https://github.com/FAQGURU/FAQGURU/blob/master/topics/en/react.md#whats-an-alternative-way-to-avoid-having-to-bind-to-this-in-event-callback-methods-senior) question—and a few others, you should probably just delete them, or point straight to a resource that answers them in detail. Simply saying “Use arrow functions in your event handlers.” isn’t enough. In fact, in most cases, the next question interviewers ask is “what’s the downside of using the method you just mentioned”? You _should_ also talk about the performance issues with passing an arrow function as a callback to the event handlers. I’m bringing this up because the next resource you point to _also_ fails to bring that up 😅

Thanks for working on this resource! 💖

**Comment by TechiePriyaRanjan** [comment]
I would like to thank you for pointing out some points in your issue, but I think (and probably most would) that quality questions is more important than answers; I would like to repeat what _Thomas J. Watson_ 
has said,  **“The ability to ask the right question is more than half the battle of finding the answer.”**  
Because in way to finding answers to that particular question whose answer you didn't find, you will look hundreds of resources to that solution🙂. 
Nevertheless, you can always make a pull request and add your detailed answers to the questions you feel has not perfect answer. you can also provide alternative answer to the same question, that will help in looking into the problem in some other perspective 😉.
**“Quality questions create a quality life. Successful people ask better questions, and as a result, they get better answers.”** _-Anthony Robbins_

**Comment by uliaaan** [comment]
Thanks for feedback. We removed all levels...
